### ISSUE TITLE
openwrt 可以用吗？

### ISSUE THREAD

**Issue by to-free** [pmkol/easymosdns#1]
openwrt 可以用吗？

**Comment by pmkol** [comment]
Linux系统理论都支持，因为用的是linux通用的shell语句，但因为每个发行版不同，有的命令可能需要支撑。

比如脚本里用到了chmod命令，我记得openwrt那个没任何功能的原版好像不支持chmod，需要安装插件来支持，但一般由第三方做好的固件，都会支持，你可以测试一下

**Comment by bergy010** [comment]
windows 可以用吗？

**Comment by pmkol** [comment]
> windows 可以用吗？

用不了的，只支持linux
