### ISSUE TITLE
建议对于本地DNS解析不要只使用alidns

### ISSUE THREAD

**Issue by liangxyz** [pmkol/easymosdns#12]
如题，最开始发现有问题是因为https://www.423down.com/ ，alidns直接无解析，我使用在线dns检查工具以后发现网站能正常访问，所以在本地解析手动添加了其他dns后就能正常访问了

**Comment by pmkol** [comment]
nslookup www.423down.com 223.5.5.5
服务器:  public1.alidns.com
Address:  223.5.5.5

非权威应答:
名称:    www.423down.com
Address:  101.32.11.178

我本地测试的结果，未发现问题，中国境内网络环境复杂，遇到ALIDNS有问题可以通过脚本切换成DNSPOD
