### ISSUE TITLE
请教一下“自动更新缓存” 功能指的是什么？

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [pmkol/easymosdns#13]
请教一下“自动更新缓存” 功能指的是什么？

是类似 smartdns 的”域名预读取“，还是只是清理 Redis 中的数据？

**Comment by pmkol** [comment]
lazy cache 的设计参考了 RFC 8767。所有应答都会在缓存中存留 lazy_cache_ttl 秒，但自身的 TTL 仍然有效。
如果命中过期的应答，则缓存会立即返回 TTL 为 lazy_cache_reply_ttl 的应答，然后自动在后台发送请求更新数据。
相比强行增加应答自身的 TTL 的方法，lazy cache 能提高命中率，同时还能保持一定的数据新鲜度。

详细请见程序官方wiki：
https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns/cha-jian-ji-qi-can-shu#cache-huan-cun

**Comment by wy16W2pIilK1xgqN** [comment]
谢谢回复，明白你的意思了。
我误以为本项目自己实现了一个解析更新方案。
感谢你的指点。
o(*^＠^*)o
