### ISSUE TITLE
redis数据库连接成功是否可以加入提示

### ISSUE THREAD

**Issue by avsba001** [pmkol/easymosdns#14]
include.conf内redis dir我填写格式为redis_dir="redis://192.168.20.86:6379/12346"  redis://ip:端口/密码
但我发现密码栏任意填写，shell都提示running和enable，可以加入连接验证嘛

**Comment by pmkol** [comment]
暂时没有考虑加入，因为这只是一个方便部署的脚本。

**Comment by mjyhj** [comment]
> include.conf内redis dir我填写格式为redis_dir="redis://192.168.20.86:6379/12346" redis://ip:端口/密码 但我发现密码栏任意填写，shell都提示running和enable，可以加入连接验证嘛

端口后面的不是密码，是db的num。
# TCP 连接: `redis://<user>:<password>@<host>:<port>/<db_number>`

**Comment by avsba001** [comment]
> 
感谢，让我搜到了示例
