### ISSUE TITLE
感谢提供，请教一下与asn.bgp.space的异同

### ISSUE THREAD

**Issue by xuesumin** [pmkol/easymosdns#15]
谢谢您提供的mosdns应用，确实很方便。
想请教您一个问题，用于ssr plus或者passwall这类国内IP库的更新源，
您这个IP库与https://asn.bgp.space/
的区别？推荐哪些更新IP库

**Comment by pmkol** [comment]
https://github.com/pmkol/easymosdns/tree/rules
参考这个项目，里面标有每个规则的数据来源
