### ISSUE TITLE
能否增加远程上游Cloudflare DNS

### ISSUE THREAD

**Issue by weiyakeji** [pmkol/easymosdns#17]
能否增加远程上游Cloudflare DNS
TUNADNS和GeekDNS不太好用
麻烦大佬考虑一下

**Comment by pmkol** [comment]
Cloudflare DNS 由于不支持ECS功能，且在中国大陆访问绕道体验极差，会导致解析的结果不准确，所以暂不会考虑增加，未来会考虑把我自建的DOH添加进来。

你也可以临时将config.yaml中的168行，
geekdns的地址
tls://v.233py.com:853
更改为
https://doh.apad.pro/dns-query

然后使用脚本将上游DNS切换为geekdns使用，此时使用的就是我的DOH了

**Comment by weiyakeji** [comment]
确实，cf不支持ecs，我试试，感谢大佬
