### ISSUE TITLE
关于ecs的问题

### ISSUE THREAD

**Issue by weiyakeji** [pmkol/easymosdns#18]
大佬，我又来打扰了，我有个疑问，远程dns查询携带的ecs信息是台湾或者日本，那么我就有一个疑问，我的代理服务在美西，这样理论上是不是就有点绕路了？

是不是让ecs信息是美西最佳？

**Comment by pmkol** [comment]
ECS中，只有强制远程解析列表中的域名，会附带台湾的ECS信息，其他的只会附带大陆的ECS信息，目前GFWLIST列表中的域名，使用的ECS子网是1.2.4.0/24，一般会给被墙域名分配中国大陆的周边的CDN节点。

如果你使用的GFWLIST模式的代理，则可以将ecs_cn这个子网信息，修改成你代理服务器的子网信息。

如果你使用的是白名单模式的代理，config.yaml中294行的IP判断处的ecs也应修改为你代理服务器的子网信息，即将ecs_global修改为ecs_cn，ecs_cn的子网IP修改为代理服务器的子网IP。

这样可以实现最优的访问速度。

**Comment by weiyakeji** [comment]
我明白了，感谢大佬给与详细解答。
看来这个要实现起来还是需要跟代理工具那边的规则配套，不然总归是有误判的。

**Comment by weiyakeji** [comment]
我看了下配置，我的mosdns是部署在内网，关闭ecs时，好像注解了294行的参数，这个可以打开？

**Comment by pmkol** [comment]
> 我看了下配置，我的mosdns是部署在内网，关闭ecs时，好像注解了294行的参数，这个可以打开？

关闭是为防止对外发送内网IP导致解析错误，当定义了指定的外网IP后，是可以打开的

**Comment by weiyakeji** [comment]
> > 我下，我的mosdn是部署配置网络，关闭ecs时，好像解开了294行的，可以打开吗？
> 
> 关闭是因为阻止发送内网IP导致解析错误，当定义了指定的外网IP后，是可以打开的

明白了，已经按照大佬指点做了相应修改，大部分已知被gfw墙的域名访问很流畅，我的代理配置的是介于gfw模式和白名单模式之间，我把一些已知的规则库，走代理，规则匹配不到的漏网域名域名走本地，漏网的域名似乎有一点影响，不过好在日常碰到的几率也不大。
再次感谢大佬指点
