### ISSUE TITLE
使用geosite.dat和geoip.dat替换项目rule规则

### ISSUE THREAD

**Issue by rhettor** [pmkol/easymosdns#19]
mosdns v2dat命令支持将v2ray data转换成txt文件，是否考虑可以通过更新geosite.dat和geoip.dat源文件，通过mosdns v2dat转换的txt文件来替换项目rule规则

**Comment by pmkol** [comment]
rule规则每天自动更新，其中已包含geosite.dat的分流规则，geoip.dat经测试并不适用于DNS服务，所以才没有使用这两个源文件，如需使用可自行更改源码替换。
