### ISSUE TITLE
有个别站打不开

### ISSUE THREAD

**Issue by weiyakeji** [pmkol/easymosdns#21]
大佬，我遇到一个现象，https://affyun.com 这个站，查看dns返回的结果跟运营商返回的结果是一样的。但确打不开页面。错误代码连接到 affyun.com 时发生错误。PR_END_OF_FILE_ERROR

但是我手动设置位运营商的dns，不用mosdns，站点打开就很正常。

这是什么问题？

**Comment by weiyakeji** [comment]
应该找到原因了，应该是强制携带ecs信息导致的，关掉ecs就正常了

**Comment by weiyakeji** [comment]
今天这个站又不能打开了，ecs是关闭的，好奇怪

**Comment by pmkol** [comment]
DNS只负责解析域名，不负责打开网站，经过测试，这个域名国内是被污染状态，海外使用了CloudFlare的CDN，使用与项目同规则的DNS查询，结果已经正确的指向了海外节点的IP，打不开是分配的CDN节点延迟问题，建议通过代理访问，或通过hosts将域名指向一个低延迟的节点

**Comment by weiyakeji** [comment]
我就是很奇怪，用运营商的dns他这个站点就能正常打开，我强制就代理看看，多谢

**Comment by weiyakeji** [comment]
强制代理没问题了，多谢，大概就是cf cdn的锅了
