### ISSUE TITLE
mosdns v5貌似配置文件不兼容

### ISSUE THREAD

**Issue by Stonestonestone** [pmkol/easymosdns#25]
您好，我是docker运行通过watchtower自动更新latest,昨晚mosdns更新了5.0，docker运行报错，我看了下貌似配置文件存在兼容问题，目前只能看到是`data_providers`这块的报错；
![图片](https://user-images.githubusercontent.com/26944865/212508501-ed95b4cd-97fd-4441-954f-a12334d0c105.png)

**Comment by pmkol** [comment]
该项目不支持V5版本

**Comment by wwng2333** [comment]
一样，装了启动不了，研究半天发现自动安装的是5.0.0，降到4.x就正常工作了

**Comment by ceeim** [comment]
目前用的 mosdns V5，想尝试自己部署 easymosdns 发现不支持，但测试了一下作者搭建的 DoH 服务器觉得还不错，希望可以增加 V5 以及 Docker 支持。

**Comment by hu3rror** [comment]
请问后续会考虑支持 V5 吗？如果不支持 V5 是因为 V5 有什么大更改导致无法运行？
