### ISSUE TITLE
使用3.0版还是看见dns泄露

### ISSUE THREAD

**Issue by thang009** [pmkol/easymosdns#27]
昨天尝试在本地局域网搭建了一下使用,感觉很不错,非常感谢.只不过用https://browserleaks.com/dns 检测还是存在dns泄露的问题.后来尝试把分流服务器改成其他上游dns服务器后泄露就不存在了.改回默认的分流服务器又发生泄露.但是单独使用分流服务器的doh也不会出现dns泄露,我是在centos8上搭的

**Comment by pmkol** [comment]
已经修复了，mosdns自身对doh超时判断的问题，导致本地分流器一直启动产生的泄露

**Comment by thang009** [comment]
经测试已经没问题了,感谢修复
