### ISSUE TITLE
gfw_ip_list.txt 包含一些没有被墙的 IP

### ISSUE THREAD

**Issue by Journalist-HK** [pmkol/easymosdns#29]
我自己的配置里用了 gfw_ip_list.txt，看日志 edge.microsoft.com 的 IP 204.79.197.239 并没有被墙，但是会撞到规则。能否去除 204.79.197.0/24？

**Comment by pmkol** [comment]
不需要去除，这个IP段有部分IP是污染返回的IP，在分流规则中并不会因为碰到产生二次解析
