### ISSUE TITLE
可以在局域网内搭建一个吗

### ISSUE THREAD

**Issue by mrzj110** [pmkol/easymosdns#3]
可以在局域网内搭建一个吗

**Comment by pmkol** [comment]
当然可以，前提是你的内网要有网络，内网记得用脚本关闭ECS功能

**Comment by mrzj110** [comment]
> 当然可以，前提是你的内网要有网络，内网记得用脚本关闭ECS功能
客户端直接填写服务端的ip吗

**Comment by pmkol** [comment]
> > 当然可以，前提是你的内网要有网络，内网记得用脚本关闭ECS功能
> > 客户端直接填写服务端的ip吗

你的客户端，指的是你在同内网段下的手机电脑等设备么？如果是，我更建议你把路由器的内网DNS改成内网DNS服务器的，而不是动客户端设备

**Comment by mrzj110** [comment]
> > > 当然可以，前提是你的内网要有网络，内网记得用脚本关闭ECS功能
> > > 客户端直接填写服务端的ip吗
> 
> 你的客户端，指的是你在同内网段下的手机电脑等设备么？如果是，我更建议你把路由器的内网DNS改成内网DNS服务器的，而不是动客户端设备
我跟着你的文章教程centos7搭建的一个，但是直接dns改成服务端ip解析不了（客户端是内网的）

**Comment by pmkol** [comment]
> > > > 当然可以，前提是你的内网要有网络，内网记得用脚本关闭ECS功能
> > > > 客户端直接填写服务端的ip吗
> > 
> > 
> > 你的客户端，指的是你在同内网段下的手机电脑等设备么？如果是，我更建议你把路由器的内网DNS改成内网DNS服务器的，而不是动客户端设备
> > 我跟着你的文章教程centos7搭建的一个，但是直接dns改成服务端ip解析不了（客户端是内网的）

1、首先使用客户端，确认内网dns是否能Ping通

2、如果能ping通，ssh进入linux命令行
dig @127.0.0.1 -p 53 www.baidu.com

3、如果上面没结果，检查一下mosdns是否正常工作，如果上面的操作有解析结果，检查一下防火墙的UDP和TCP端口是否已打开，另外内网部署，必须关闭ECS功能

**Comment by mrzj110** [comment]
> > > > > 当然可以，前提是你的内网要有网络，内网记得用脚本关闭ECS功能
> > > > > 客户端直接填写服务端的ip吗
> > > 
> > > 
> > > 你的客户端，指的是你在同内网段下的手机电脑等设备么？如果是，我更建议你把路由器的内网DNS改成内网DNS服务器的，而不是动客户端设备
> > > 我跟着你的文章教程centos7搭建的一个，但是直接dns改成服务端ip解析不了（客户端是内网的）
> 
> 1、首先使用客户端，确认内网dns是否能Ping通
> 
> 2、如果能ping通，ssh进入linux命令行 dig @127.0.0.1 -p 53 [www.baidu.com](http://www.baidu.com)
> 
> 3、如果上面没结果，检查一下mosdns是否正常工作，如果上面的操作有解析结果，检查一下防火墙的UDP和TCP端口是否已打开，另外内网部署，必须关闭ECS功能

可以了，是防火墙端口没打开
