### ISSUE TITLE
请教CN域名来源

### ISSUE THREAD

**Issue by SeaHOH** [pmkol/easymosdns#4]
对比了 [felixonmars/dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list)，总体一致，但有多处增删。
请问是另有数据来源呢，还是经过了特定的方法验证处理？能否公开下这份数据的生成方式？

特此叩谢，望不吝指教。

**Comment by pmkol** [comment]
CN域名，来源于[geosite](https://github.com/Loyalsoldier/v2ray-rules-dat)
最早因为一些海外产品被污染的API接口域名，我在其他库里，都没有找到。因为CN库要匹配gfwlist域名，就统一用了一个库。而且目前来说，geosite的CN库应该是较准的库之一。

**Comment by pmkol** [comment]
对比了一下你提供的项目，geosite应该是少了一个[removed-cdn.txt](https://github.com/felixonmars/dnsmasq-china-list/blob/master/removed-cdn.txt)列表，晚些我会补充这个名单

**Comment by SeaHOH** [comment]
感谢！
removed-cdn.txt 列表用来分流完全没问题，不过域名本身不全都属于 CN。

**Comment by pmkol** [comment]
> 感谢！ removed-cdn.txt 列表用来分流完全没问题，不过域名本身不全都属于 CN。

规则已经更新完成，考虑到灵活使用，已将CDN列表独立出来
