### ISSUE TITLE
请问如何更新程序本身？

### ISSUE THREAD

**Issue by weiyakeji** [pmkol/easymosdns#5]
整个框架自身应该怎么更新呢？

**Comment by pmkol** [comment]
直接覆盖即可

**Comment by weiyakeji** [comment]
好的，多谢解答.
另外,我建议关于中国IP库的列表更换一个源,目前这个源不是很精确,尤其是会导致苹果手机商店异常,这个异常发生在中国区账号上,美区账号没什么问题,我自己更换了IP库后,目前好多了.

我用ros的路由系统,用到策略分流,也有引用中国IP库,我用过很多,综合来说,这个站的准确率最高,所以,如果可能,请用这个站的IP库
http://www.iwik.org/ipcountry/CN.cidr
http://www.iwik.org/ipcountry/CN.ipv6

**Comment by pmkol** [comment]
这个有数据来源么？目前IP表使用的是IPIP+纯真+BGP，准确度理论上很高了。
你的数据里包含了香港IP，例如118.184.0.0/17，这其中就包含了污染IP 118.184.26.113 与 118.184.78.78，所以是没用办法作为IP分流表使用的，不然容易造成污染。
苹果中国区商店的异常问题，我这边目前没有发现，你可以用我的doh测试一下，看看是否也异常。

**Comment by weiyakeji** [comment]
哦，具体他的数据来源我不清楚，但他这个站也提供好几年了，反正我在ros策略分流的使用上还是别叫稳定精确的，理论上ipip+纯真+bgp是比较全的了，目前我ros分流引用的库是iwik.org+IPip+纯真+apnic做了一个简单的去重来使用，目前使用良好。

我再观察观察，之前使用良好，就是苹果中国区账号下载app有问题，因为我家里都是用苹果手机，我自己的是美区id，其他人是国区id，所以，在ros做分流时，大多数库都多少有点问题，无论单独用ipip，还是纯真。单独使用iwik.org就没什么问题，后来索性把几个库合起来，其实我知道合起来没什么大作用。

还是非常感谢你的解答，这个库我先自己生成，在用你的doh做下对比，看看到底问题出在什么地方。

**Comment by pmkol** [comment]
> 哦，具体他的数据来源我不清楚，但他这个站也提供好几年了，反正我在ros策略分流的使用上还是别叫稳定精确的，理论上ipip+纯真+bgp是比较全的了，目前我ros分流引用的库是iwik.org+IPip+纯真+apnic做了一个简单的去重来使用，目前使用良好。
> 
> 我再观察观察，之前使用良好，就是苹果中国区账号下载app有问题，因为我家里都是用苹果手机，我自己的是美区id，其他人是国区id，所以，在ros做分流时，大多数库都多少有点问题，无论单独用ipip，还是纯真。单独使用iwik.org就没什么问题，后来索性把几个库合起来，其实我知道合起来没什么大作用。
> 
> 还是非常感谢你的解答，这个库我先自己生成，在用你的doh做下对比，看看到底问题出在什么地方。

可以找一下是哪个域名的问题，问了一下使用我DNS的人，暂时都未发现苹果商店有问题，可能是个例，这种情况可以把商店的域名加入中国区名单，如果可以的话把域名找出来，我加到每日更新的规则中。
