### ISSUE TITLE
请问大神如何在软路由安装？

### ISSUE THREAD

**Issue by ghost** [pmkol/easymosdns#6]
大神你好，我有个openwrt的X86软路由，请问如何安装？

**Comment by pmkol** [comment]
推荐你看下
https://github.com/sbwml/luci-app-mosdns

这个项目应该更适合软路由使用，可以用我的配置文件和规则库在这个项目的基础上做补充

**Comment by ghost** [comment]
> 推荐你看下 https://github.com/sbwml/luci-app-mosdns
> 
> 这个项目应该更适合软路由使用，可以用我的配置文件和规则库在这个项目的基础上做补充

谢谢大神的回复，我把您的配置还有规则导入，做了修改，可是没有mosdns没有运行，不知道哪里出了差错

**Comment by pmkol** [comment]
已在另一个问题中做出回复，这个问题关闭了
