### ISSUE TITLE
> 推荐你看下 https://github.com/sbwml/luci-app-mosdns

### ISSUE THREAD

**Issue by ghost** [pmkol/easymosdns#8]
> 推荐你看下 https://github.com/sbwml/luci-app-mosdns
> 
> 这个项目应该更适合软路由使用，可以用我的配置文件和规则库在这个项目的基础上做补充

谢谢大神的回复，我把您的配置还有规则导入，做了修改，可是mosdns没有运行，不知道哪里出了差错

_Originally posted by @wenju88 in https://github.com/pmkol/easymosdns/issues/6#issuecomment-1191055269_

**Comment by pmkol** [comment]
规则应该无法直接导入，你可以用这个项目默认的规则，然后下载调用我做的rules规则文件，这样对于新手简单一些。

**Comment by ghost** [comment]
> 规则应该无法直接导入，你可以用这个项目默认的规则，然后下载调用我做的rules规则文件，这样对于新手简单一些。

谢谢兄台
