### ISSUE TITLE
能否做一个全局ipv4结果优先的切换脚本

### ISSUE THREAD

**Issue by weiyakeji** [pmkol/easymosdns#9]
大佬，你好，能否做一个全局ipv4优先切换脚本，主要是现在ipv6国内还是比较不健全，想国内查询也用ipv4结果优先。
或者我应该修改配置文件里那些位置，我添加了，似乎无效。

**Comment by pmkol** [comment]
修改config.yaml文件以下两处即可

        # 已知的本地域名或CDN域名用本地服务器解析
        - if: "(query_is_local_domain) || (query_is_cdn_cn_domain)"
          exec:
            - _prefer_ipv4
            - ecs_auto
            - forward_alidns
            - _return

          # primary 从本地服务器获取应答，丢弃非本地IP或污染IP的结果
        - primary:
            - _prefer_ipv4
            - ecs_auto
            - forward_local
            - ttl_short
            - if: "(! response_has_local_ip) && [_response_valid_answer] || (response_has_gfw_ip)"
              exec:
                - _drop_response

**Comment by weiyakeji** [comment]
收到，感谢大佬，我也是加载这个位置，可能是缓存的原因，没及时生效。

**Comment by pmkol** [comment]
不仅要清空DNS缓存，客户端的缓存也要清空的
